version: '3'

volumes:
  local_basementjam_postgres_data: {}

services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - local_basementjam_postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      poetry run hypercorn --reload --bind 0.0.0.0:8000 app.main:app
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: "LOCAL"
    depends_on:
      - db
